export const ROLES = {
  ADMIN: 'ADMIN',
  POLICE_OFFICER: 'POLICE_OFFICER',
  INVESTIGATOR: 'INVESTIGATOR',
  FORENSIC_OFFICER: 'FORENSIC_OFFICER',
  LEGAL_OFFICER: 'LEGAL_OFFICER',
  COURT_USER: 'COURT_USER',
} as const;

export type UserRole = (typeof ROLES)[keyof typeof ROLES];

export const DEPARTMENTS = {
  POLICE: 'POLICE',
  INVESTIGATION: 'INVESTIGATION',
  FORENSICS: 'FORENSICS',
  LEGAL: 'LEGAL',
  JUDICIARY: 'JUDICIARY',
  ADMIN: 'ADMIN',
} as const;

export const CASE_STATUS = {
  REGISTERED: 'REGISTERED',
  UNDER_INVESTIGATION: 'UNDER_INVESTIGATION',
  FORENSIC_ANALYSIS: 'FORENSIC_ANALYSIS',
  LEGAL_REVIEW: 'LEGAL_REVIEW',
  COURT_SUBMITTED: 'COURT_SUBMITTED',
  CLOSED: 'CLOSED',
} as const;

export const CASE_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;

export const DOCUMENT_TYPES = {
  FIR: 'FIR',
  POLICE_REPORT: 'POLICE_REPORT',
  INVESTIGATION_REPORT: 'INVESTIGATION_REPORT',
  EVIDENCE: 'EVIDENCE',
  FORENSIC_REPORT: 'FORENSIC_REPORT',
  WITNESS_STATEMENT: 'WITNESS_STATEMENT',
  LEGAL_DOCUMENT: 'LEGAL_DOCUMENT',
  COURT_DOCUMENT: 'COURT_DOCUMENT',
  OTHER: 'OTHER',
} as const;

export const DOCUMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
  INVALID: 'INVALID',
} as const;

export const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CASE_CREATED: 'CASE_CREATED',
  CASE_UPDATED: 'CASE_UPDATED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_VIEWED: 'DOCUMENT_VIEWED',
  DOCUMENT_DOWNLOADED: 'DOCUMENT_DOWNLOADED',
  DOCUMENT_SHARED: 'DOCUMENT_SHARED',
  SHARE_REVOKED: 'SHARE_REVOKED',
  DOCUMENT_UPDATED: 'DOCUMENT_UPDATED',
  VERSION_CREATED: 'VERSION_CREATED',
  DOCUMENT_ARCHIVED: 'DOCUMENT_ARCHIVED',
  DOCUMENT_INVALIDATED: 'DOCUMENT_INVALIDATED',
  INTEGRITY_CHECK: 'INTEGRITY_CHECK',
  AI_SUMMARY_GENERATED: 'AI_SUMMARY_GENERATED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  METADATA_UPDATED: 'METADATA_UPDATED',
} as const;

export const EVIDENCE_STATUS = {
  COLLECTED: 'COLLECTED',
  IN_CUSTODY: 'IN_CUSTODY',
  LAB_ANALYSIS: 'LAB_ANALYSIS',
  COURT_SUBMITTED: 'COURT_SUBMITTED',
  DISPOSED: 'DISPOSED',
} as const;
